name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install
      run: sudo apt-get install tree
    - name: Version check
      run: rustc --version
    - name: Build
      run: cargo build --verbose
    - name: tree
      run: tree
    - name: Execute
      run: target/debug/hello_cargo
    - name: Run tests
      run: cargo test --verbose
