name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Version check
      run: rust --version
    - name: Build
      run: cargo build --verbose
    - name: Execute
      run: ./hello_cargo
    - name: Run tests
      run: cargo test --verbose
